[project]
name = "disease-informer-locales"
version = "1.0.0"
description = "Localizations for the Disease Informer bot."
readme = "README.md"
requires-python = ">=3.13.0"

[dependency-groups]
localization = [
  "compare-locales>=9.0.4",
]
