name: Lint and compare locales

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
            enable-cache: true

      - name: Check lint
        run: uv run --group localization moz-l10n-lint l10n.toml

      - name: Compare locales
        run: uv run --group localization compare-locales l10n.toml locales
